// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Sho_2DPW2Bi_r3PPsMsfkjooKL4p8GU',
    appId: '1:1023680758521:web:55a32ee3f0b264d4c45828',
    messagingSenderId: '1023680758521',
    projectId: 'healthonify-7506a',
    authDomain: 'healthonify-7506a.firebaseapp.com',
    storageBucket: 'healthonify-7506a.appspot.com',
    measurementId: 'G-7ZK5CCJPZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD4OWezjPGXRz3EqCF8-X6i_X6c-vtpqc',
    appId: '1:1023680758521:android:5de7153f0fee0521c45828',
    messagingSenderId: '1023680758521',
    projectId: 'healthonify-7506a',
    storageBucket: 'healthonify-7506a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArNhzOaHObh1qBm3piYa1KWYIr2oW1wI0',
    appId: '1:1023680758521:ios:80c4281056186339c45828',
    messagingSenderId: '1023680758521',
    projectId: 'healthonify-7506a',
    storageBucket: 'healthonify-7506a.appspot.com',
    iosClientId: '1023680758521-p7a6199js4r9tpeandkvql0dqke815hc.apps.googleusercontent.com',
    iosBundleId: 'com.octal.healthonifyMobile',
  );
}
